SetPrivateProfileString('Progress Bar','Full Red','128')
SetPrivateProfileString('Progress Bar','IniOptionsSet','1')
SetPrivateProfileString('Progress Bar','Full Blue','0')
SetPrivateProfileString('Progress Bar','Color Green','0')
SetPrivateProfileString('Progress Bar','Full Green','0')
SetPrivateProfileString('Progress Bar','Color Blue','0')
SetPrivateProfileString('Progress Bar','Color Red','128')
SetPrivateProfileString('Fonts','Zoom','125')
SetPrivateProfileString('Fonts','ru_RU','PTSERIF')
SetPrivateProfileString('Fonts','ja_JP','MEIRYO')
SetPrivateProfileString('Fonts','ko_KR','NANUM')
SetPrivateProfileString('Fonts','zh_CN','SIMSUN')
SetPrivateProfileString('Fonts','uk_UA','PERMIAN')
SetPrivateProfileString('Mage Spells','SPWI910','0')
SetPrivateProfileString('Mage Spells','SPWI222','0')
SetPrivateProfileString('Mage Spells','SPWI713','0')
SetPrivateProfileString('Mage Spells','SPWI117','0')
SetPrivateProfileString('Mage Spells','SPWI508','0')
SetPrivateProfileString('Mage Spells','SPWI407','0')
SetPrivateProfileString('Mage Spells','SPWI217','0')
SetPrivateProfileString('Mage Spells','SPWI411','0')
SetPrivateProfileString('Mage Spells','SPWI502','0')
SetPrivateProfileString('Mage Spells','SPWI423','0')
SetPrivateProfileString('Mage Spells','SPWI514','0')
SetPrivateProfileString('Mage Spells','SPWI803','0')
SetPrivateProfileString('Mage Spells','SPWI623','0')
SetPrivateProfileString('Mage Spells','SPWI103','0')
SetPrivateProfileString('Mage Spells','SPWI413','0')
SetPrivateProfileString('Mage Spells','SPWI616','0')
SetPrivateProfileString('Mage Spells','SPWI408','0')
SetPrivateProfileString('Mage Spells','SPWI310','0')
SetPrivateProfileString('Mage Spells','SPWI702','0')
SetPrivateProfileString('Mage Spells','SPWI105','0')
SetPrivateProfileString('Mage Spells','SPWI811','0')
SetPrivateProfileString('Mage Spells','SPWI125','0')
SetPrivateProfileString('Mage Spells','SPWI518','0')
SetPrivateProfileString('Mage Spells','SPWI818','0')
SetPrivateProfileString('Mage Spells','SPWI618','0')
SetPrivateProfileString('Mage Spells','SPWI301','0')
SetPrivateProfileString('Mage Spells','SPWI809','0')
SetPrivateProfileString('Mage Spells','SPWI321','0')
SetPrivateProfileString('Mage Spells','SPWI113','0')
SetPrivateProfileString('Mage Spells','SPWI903','0')
SetPrivateProfileString('Mage Spells','SPWI224','0')
SetPrivateProfileString('Mage Spells','SPWI418','0')
SetPrivateProfileString('Mage Spells','SPWI501','0')
SetPrivateProfileString('Mage Spells','SPWI707','0')
SetPrivateProfileString('Mage Spells','SPWI309','0')
SetPrivateProfileString('Mage Spells','SPWI207','0')
SetPrivateProfileString('Mage Spells','SPWI118','0')
SetPrivateProfileString('Mage Spells','SPWI808','0')
SetPrivateProfileString('Mage Spells','SPWI124','0')
SetPrivateProfileString('Mage Spells','SPWI914','0')
SetPrivateProfileString('Mage Spells','SPWI601','0')
SetPrivateProfileString('Mage Spells','SPWI617','0')
SetPrivateProfileString('Mage Spells','SPWI506','0')
SetPrivateProfileString('Mage Spells','SPWI523','0')
SetPrivateProfileString('Mage Spells','SPWI622','0')
SetPrivateProfileString('Mage Spells','SPWI603','0')
SetPrivateProfileString('Mage Spells','SPWI417','0')
SetPrivateProfileString('Mage Spells','SPWI307','0')
SetPrivateProfileString('Mage Spells','SPWI403','0')
SetPrivateProfileString('Mage Spells','SPWI305','0')
SetPrivateProfileString('Mage Spells','SPWI608','0')
SetPrivateProfileString('Mage Spells','SPWI620','0')
SetPrivateProfileString('Mage Spells','SPWI509','0')
SetPrivateProfileString('Mage Spells','SPWI115','0')
SetPrivateProfileString('Mage Spells','SPWI312','0')
SetPrivateProfileString('Mage Spells','SPWI318','0')
SetPrivateProfileString('Mage Spells','SPWI905','0')
SetPrivateProfileString('Mage Spells','SPWI917','0')
SetPrivateProfileString('Mage Spells','SPWI621','0')
SetPrivateProfileString('Mage Spells','SPWI313','0')
SetPrivateProfileString('Mage Spells','SPWI101','0')
SetPrivateProfileString('Mage Spells','SPWI913','0')
SetPrivateProfileString('Mage Spells','SPWI704','0')
SetPrivateProfileString('Mage Spells','SPWI425','0')
SetPrivateProfileString('Mage Spells','SPWI609','0')
SetPrivateProfileString('Mage Spells','SPWI205','0')
SetPrivateProfileString('Mage Spells','SPWI420','0')
SetPrivateProfileString('Mage Spells','SPWI817','0')
SetPrivateProfileString('Mage Spells','SPWI119','0')
SetPrivateProfileString('Mage Spells','SPWI723','0')
SetPrivateProfileString('Mage Spells','SPWI306','0')
SetPrivateProfileString('Mage Spells','SPWI805','0')
SetPrivateProfileString('Mage Spells','SPWI424','0')
SetPrivateProfileString('Mage Spells','SPWI219','0')
SetPrivateProfileString('Mage Spells','SPWI209','0')
SetPrivateProfileString('Mage Spells','SPWI711','0')
SetPrivateProfileString('Mage Spells','SPWI303','0')
SetPrivateProfileString('Mage Spells','SPWI615','0')
SetPrivateProfileString('Mage Spells','SPWI212','0')
SetPrivateProfileString('Mage Spells','SPWI111','0')
SetPrivateProfileString('Mage Spells','SPWI604','0')
SetPrivateProfileString('Mage Spells','SPWI415','0')
SetPrivateProfileString('Mage Spells','SPWI710','0')
SetPrivateProfileString('Mage Spells','SPWI810','0')
SetPrivateProfileString('Mage Spells','SPWI320','0')
SetPrivateProfileString('Mage Spells','SPWI414','0')
SetPrivateProfileString('Mage Spells','SPWI718','0')
SetPrivateProfileString('Mage Spells','SPWI705','0')
SetPrivateProfileString('Mage Spells','SPWI907','0')
SetPrivateProfileString('Mage Spells','SPWI915','0')
SetPrivateProfileString('Mage Spells','SPWI102','0')
SetPrivateProfileString('Mage Spells','SPWI316','0')
SetPrivateProfileString('Mage Spells','SPWI202','0')
SetPrivateProfileString('Mage Spells','SPWI210','0')
SetPrivateProfileString('Mage Spells','SPWI106','0')
SetPrivateProfileString('Mage Spells','SPWI606','0')
SetPrivateProfileString('Mage Spells','SPWI812','0')
SetPrivateProfileString('Mage Spells','SPWI215','0')
SetPrivateProfileString('Mage Spells','SPWI116','0')
SetPrivateProfileString('Mage Spells','SPWI218','0')
SetPrivateProfileString('Mage Spells','SPWI201','0')
SetPrivateProfileString('Mage Spells','SPWI206','0')
SetPrivateProfileString('Mage Spells','SPWI612','0')
SetPrivateProfileString('Mage Spells','SPWI208','0')
SetPrivateProfileString('Mage Spells','SPWI311','0')
SetPrivateProfileString('Mage Spells','SPWI522','0')
SetPrivateProfileString('Mage Spells','SPWI919','0')
SetPrivateProfileString('Mage Spells','SPWI701','0')
SetPrivateProfileString('Mage Spells','SPWI104','0')
SetPrivateProfileString('Mage Spells','SPWI112','0')
SetPrivateProfileString('Mage Spells','SPWI513','0')
SetPrivateProfileString('Mage Spells','SPWI213','0')
SetPrivateProfileString('Mage Spells','SPWI319','0')
SetPrivateProfileString('Mage Spells','SPWI326','0')
SetPrivateProfileString('Mage Spells','SPWI708','0')
SetPrivateProfileString('Mage Spells','SPWI918','0')
SetPrivateProfileString('Mage Spells','SPWI619','0')
SetPrivateProfileString('Mage Spells','SPWI507','0')
SetPrivateProfileString('Mage Spells','SPWI419','0')
SetPrivateProfileString('Mage Spells','SPWI721','0')
SetPrivateProfileString('Mage Spells','SPWI315','0')
SetPrivateProfileString('Mage Spells','SPWI712','0')
SetPrivateProfileString('Mage Spells','SPWI517','0')
SetPrivateProfileString('Mage Spells','SPWI614','0')
SetPrivateProfileString('Mage Spells','SPWI605','0')
SetPrivateProfileString('Mage Spells','SPWI908','0')
SetPrivateProfileString('Mage Spells','SPWI714','0')
SetPrivateProfileString('Mage Spells','SPWI909','0')
SetPrivateProfileString('Mage Spells','SPWI807','0')
SetPrivateProfileString('Mage Spells','SPWI512','0')
SetPrivateProfileString('Mage Spells','SPWI515','0')
SetPrivateProfileString('Mage Spells','SPWI120','0')
SetPrivateProfileString('Mage Spells','SPWI401','0')
SetPrivateProfileString('Mage Spells','SPWI911','0')
SetPrivateProfileString('Mage Spells','SPWI203','0')
SetPrivateProfileString('Mage Spells','SPWI324','0')
SetPrivateProfileString('Mage Spells','SPWI223','0')
SetPrivateProfileString('Mage Spells','SPWI214','0')
SetPrivateProfileString('Mage Spells','SPWI211','0')
SetPrivateProfileString('Mage Spells','SPWI108','0')
SetPrivateProfileString('Mage Spells','SPWI703','0')
SetPrivateProfileString('Mage Spells','SPWI516','0')
SetPrivateProfileString('Mage Spells','SPWI503','0')
SetPrivateProfileString('Mage Spells','SPWI902','0')
SetPrivateProfileString('Mage Spells','SPWI611','0')
SetPrivateProfileString('Mage Spells','SPWI613','0')
SetPrivateProfileString('Mage Spells','SPWI716','0')
SetPrivateProfileString('Mage Spells','SPWI510','0')
SetPrivateProfileString('Mage Spells','SPWI804','0')
SetPrivateProfileString('Mage Spells','SPWI715','0')
SetPrivateProfileString('Mage Spells','SPWI607','0')
SetPrivateProfileString('Mage Spells','SPWI406','0')
SetPrivateProfileString('Mage Spells','SPWI504','0')
SetPrivateProfileString('Mage Spells','SPWI317','0')
SetPrivateProfileString('Mage Spells','SPWI916','0')
SetPrivateProfileString('Mage Spells','SPWI505','0')
SetPrivateProfileString('Mage Spells','SPWI602','0')
SetPrivateProfileString('Mage Spells','SPWI314','0')
SetPrivateProfileString('Mage Spells','SPWI722','0')
SetPrivateProfileString('Mage Spells','SPWI717','0')
SetPrivateProfileString('Mage Spells','SPWI816','0')
SetPrivateProfileString('Mage Spells','SPWI302','0')
SetPrivateProfileString('Mage Spells','SPWI107','0')
SetPrivateProfileString('Mage Spells','SPWI815','0')
SetPrivateProfileString('Mage Spells','SPWI308','0')
SetPrivateProfileString('Mage Spells','SPWI123','0')
SetPrivateProfileString('Mage Spells','SPWI114','0')
SetPrivateProfileString('Mage Spells','SPWI409','0')
SetPrivateProfileString('Mage Spells','SPWI404','0')
SetPrivateProfileString('Mage Spells','SPWI110','0')
SetPrivateProfileString('Mage Spells','SPWI521','0')
SetPrivateProfileString('Mage Spells','SPWI325','0')
SetPrivateProfileString('Mage Spells','SPWI220','0')
SetPrivateProfileString('Mage Spells','SPWI720','0')
SetPrivateProfileString('Mage Spells','SPWI813','0')
SetPrivateProfileString('Mage Spells','SPWI511','0')
SetPrivateProfileString('Mage Spells','SPWI519','0')
SetPrivateProfileString('Mage Spells','SPWI719','0')
SetPrivateProfileString('Mage Spells','SPWI405','0')
SetPrivateProfileString('Mage Spells','SPWI624','0')
SetPrivateProfileString('Mage Spells','SPWI625','0')
SetPrivateProfileString('Mage Spells','SPWI402','0')
SetPrivateProfileString('Mage Spells','SPWI410','0')
SetPrivateProfileString('Mage Spells','SPWI912','0')
SetPrivateProfileString('Mage Spells','SPWI416','0')
SetPrivateProfileString('Mage Spells','SPWI412','0')
SetPrivateProfileString('Mage Spells','SPWI221','0')
SetPrivateProfileString('Mage Spells','SPWI520','0')
SetPrivateProfileString('Mage Spells','SPWI421','0')
SetPrivateProfileString('Mage Spells','SPWI304','0')
SetPrivateProfileString('Mage Spells','SPWI322','0')
SetPrivateProfileString('Keymap Page','Inventory','98')
SetPrivateProfileString('Keymap Page','Map','104')
SetPrivateProfileString('Keymap Page','Character Arbitration','0')
SetPrivateProfileString('Keymap Page','Priest Spells','116')
SetPrivateProfileString('Keymap Action','Thieving','0')
SetPrivateProfileString('Keymap Action','Special Abilities','118')
SetPrivateProfileString('Keymap Action','Group Attack','0')
SetPrivateProfileString('Keymap Action','Turn Undead','0')
SetPrivateProfileString('Keymap Action','Use Item','101')
SetPrivateProfileString('Keymap Action','Equip Melee Weapon','0')
SetPrivateProfileString('Keymap Action','Equip Range Weapon','0')
SetPrivateProfileString('Keymap Action','Trap Detection','0')
SetPrivateProfileString('Keymap Action','Battle Song','0')
SetPrivateProfileString('Keymap Action','Cast Spell','99')
SetPrivateProfileString('Keymap Action','Guard / Protect','0')
SetPrivateProfileString('Keymap Action','Group Stop','0')
SetPrivateProfileString('Keymap Action','Stealth','0')
SetPrivateProfileString('Keymap Action','Dialog','0')
SetPrivateProfileString('Language','Text','zh_CN')
SetPrivateProfileString('Graphics','Hardware Mouse Cursor','1')
SetPrivateProfileString('Graphics','version','OpenGL version 4.6.0 NVIDIA 417.35 - build XXXX')
SetPrivateProfileString('Graphics','Zoom Lock','0')
SetPrivateProfileString('Graphics','Backend','0')
SetPrivateProfileString('Graphics','Show Black Space','1')
SetPrivateProfileString('Graphics','renderer','GeForce GTX 1050 Ti/PCIe/SSE2')
SetPrivateProfileString('Graphics','Use Sprite Outlines','0')
SetPrivateProfileString('Graphics','vendor','NVIDIA Corporation')
SetPrivateProfileString('Graphics','Use Nearest Neighbour Scaling','0')
SetPrivateProfileString('Graphics','Greyscale On Pause','1')
SetPrivateProfileString('Graphics','Scale UI','0')
SetPrivateProfileString('Graphics','Use Character Highlights','1')
SetPrivateProfileString('Game Options','Attack Sounds','1')
SetPrivateProfileString('Game Options','Cheats','0')
SetPrivateProfileString('Game Options','Extra Combat Info','0')
SetPrivateProfileString('Game Options','Infravision','1')
SetPrivateProfileString('Game Options','Classic Selection Circles','1')
SetPrivateProfileString('Game Options','Message Box Top','-26')
SetPrivateProfileString('Game Options','Weather','1')
SetPrivateProfileString('Game Options','Memory Level','1')
SetPrivateProfileString('Game Options','Render Explored Map','1')
SetPrivateProfileString('Game Options','Command Sounds Frequency','2')
SetPrivateProfileString('Game Options','No Difficulty Based XP Bonus','1')
SetPrivateProfileString('Game Options','GUI Feedback Level','5')
SetPrivateProfileString('Game Options','Selection Sounds Frequency','2')
SetPrivateProfileString('Game Options','Ranged Weapon Switching','1')
SetPrivateProfileString('Game Options','All Learn Spell Info','0')
SetPrivateProfileString('Game Options','Difficulty Level','2')
SetPrivateProfileString('Game Options','Tutorial State','1')
SetPrivateProfileString('Game Options','Maximum HP','1')
SetPrivateProfileString('Game Options','Hotkeys On Tooltips','1')
SetPrivateProfileString('Game Options','Filter Games','1')
SetPrivateProfileString('Game Options','Auto Pause Center','1')
SetPrivateProfileString('Game Options','Last Save SOA','000000000-Auto-Save')
SetPrivateProfileString('Game Options','Terrain Hugging','0')
SetPrivateProfileString('Game Options','Environmental Audio','1')
SetPrivateProfileString('Game Options','Show AOE','0')
SetPrivateProfileString('Game Options','Confirm Dialog','0')
SetPrivateProfileString('Game Options','HP Over Head','0')
SetPrivateProfileString('Game Options','Suppress Extra Difficulty Damage','0')
SetPrivateProfileString('Game Options','Nightmare Bonus Gold','0')
SetPrivateProfileString('Game Options','Combat UI','0')
SetPrivateProfileString('Game Options','Duplicate Floating Text','1')
SetPrivateProfileString('Game Options','Nightmare Bonus XP','0')
SetPrivateProfileString('Game Options','Heal Party on Rest','0')
SetPrivateProfileString('Game Options','Show Date On Pause','0')
SetPrivateProfileString('Game Options','Subtitles','1')
SetPrivateProfileString('Game Options','Reverse Mouse Wheel Zoom','0')
SetPrivateProfileString('Game Options','Render Actions','0')
SetPrivateProfileString('Game Options','Mouse Scroll Speed','87')
SetPrivateProfileString('Game Options','Area Effects Density','100')
SetPrivateProfileString('Game Options','Tiles Precache Percent','100')
SetPrivateProfileString('Game Options','Over Confirm Everything','1')
SetPrivateProfileString('Game Options','WILD SURGE KEYS','0')
SetPrivateProfileString('Game Options','Bored Timeout','3000')
SetPrivateProfileString('Game Options','Extra Feedback','0')
SetPrivateProfileString('Game Options','Show Learnable Spells','1')
SetPrivateProfileString('Game Options','Quick Item Mapping','1')
SetPrivateProfileString('Game Options','Show Triggers On Tab','0')
SetPrivateProfileString('Game Options','Keyboard Scroll Speed','100')
SetPrivateProfileString('Game Options','Critical Hit Screen Shake','1')
SetPrivateProfileString('Game Options','Enable Fog','0')
SetPrivateProfileString('Game Options','Expire Trap Highlights','0')
SetPrivateProfileString('Game Options','Show Message Box Hint','1')
SetPrivateProfileString('Game Options','3E Thief Sneak Attack','0')
SetPrivateProfileString('Game Options','Render Travel Regions','0')
SetPrivateProfileString('Game Options','Auto Pause State','1689')
SetPrivateProfileString('Game Options','Journal Popups','1')
SetPrivateProfileString('Game Options','Color Circles','0')
SetPrivateProfileString('Game Options','Effect Text Level','31')
SetPrivateProfileString('Game Options','Show Character HP','1')
SetPrivateProfileString('Game Options','Pausing Map','0')
SetPrivateProfileString('Game Options','Footsteps','1')
SetPrivateProfileString('Game Options','Last Save TOB','000000004-Quick-Save-4-TOB')
SetPrivateProfileString('Game Options','Always Dither','1')
SetPrivateProfileString('Game Options','Locator Feedback Level','3')
SetPrivateProfileString('Game Options','Cleric Ranger Spells','0')
SetPrivateProfileString('Lua Edit','String3',' C:CreateCreature("edwin11")')
SetPrivateProfileString('Lua Edit','String9',' C:CreateCreature("edwin11")')
SetPrivateProfileString('Lua Edit','String2',' C:CreateCreature("edwin11")')
SetPrivateProfileString('Lua Edit','String1','C:CreateItem("sw2h01")')
SetPrivateProfileString('Lua Edit','String5',' C:CreateCreature("edwin11")')
SetPrivateProfileString('Lua Edit','String6',' C:CreateCreature("edwin11")')
SetPrivateProfileString('Lua Edit','String0',' C:CreateCreature("anomen10")')
SetPrivateProfileString('Lua Edit','String8',' C:CreateCreature("edwin11")')
SetPrivateProfileString('Lua Edit','String7',' C:CreateCreature("edwin11")')
SetPrivateProfileString('Lua Edit','String4',' C:CreateCreature("edwin11")')
SetPrivateProfileString('Keymap Quick Slots','Formation Slot 3','0')
SetPrivateProfileString('Keymap Quick Slots','Formation Slot 2','0')
SetPrivateProfileString('Keymap Quick Slots','Spell Slot 2','0')
SetPrivateProfileString('Keymap Quick Slots','Item Slot 2','0')
SetPrivateProfileString('Keymap Quick Slots','Weapon Slot 2','0')
SetPrivateProfileString('Keymap Quick Slots','Item Slot 3','0')
SetPrivateProfileString('Keymap Quick Slots','Formation Slot 5','0')
SetPrivateProfileString('Keymap Quick Slots','Select 4,5,6','0')
SetPrivateProfileString('Keymap Quick Slots','Item Slot 1','0')
SetPrivateProfileString('Keymap Quick Slots','Formation Slot 4','0')
SetPrivateProfileString('Keymap Quick Slots','Spell Slot 3','0')
SetPrivateProfileString('Keymap Quick Slots','Formation Slot 1','0')
SetPrivateProfileString('Keymap Quick Slots','Weapon Slot 1','0')
SetPrivateProfileString('Keymap Quick Slots','Select 1,2,3','0')
SetPrivateProfileString('Keymap Quick Slots','Weapon Slot 3','0')
SetPrivateProfileString('Keymap Quick Slots','Weapon Slot 4','0')
SetPrivateProfileString('Keymap Quick Slots','Spell Slot 1','0')
SetPrivateProfileString('MOVIES','DEATHAND','1')
SetPrivateProfileString('MOVIES','REST','1')
SetPrivateProfileString('MOVIES','RESTDUNG','1')
SetPrivateProfileString('MOVIES','BLACKPIT','1')
SetPrivateProfileString('MOVIES','INTRO','1')
SetPrivateProfileString('MOVIES','LOGO','1')
SetPrivateProfileString('MOVIES','INTRO15F','1')
SetPrivateProfileString('Priest Spells','SPPR208','0')
SetPrivateProfileString('Priest Spells','SPPR709','0')
SetPrivateProfileString('Priest Spells','SPPR308','0')
SetPrivateProfileString('Priest Spells','SPPR511','0')
SetPrivateProfileString('Priest Spells','SPPR150','0')
SetPrivateProfileString('Priest Spells','SPPR507','0')
SetPrivateProfileString('Priest Spells','SPPR504','0')
SetPrivateProfileString('Priest Spells','SPPR408','0')
SetPrivateProfileString('Priest Spells','SPPR613','0')
SetPrivateProfileString('Priest Spells','SPPR722','0')
SetPrivateProfileString('Priest Spells','SPPR411','0')
SetPrivateProfileString('Priest Spells','SPPR417','0')
SetPrivateProfileString('Priest Spells','SPPR318','0')
SetPrivateProfileString('Priest Spells','SPPR110','0')
SetPrivateProfileString('Priest Spells','SPPR502','0')
SetPrivateProfileString('Priest Spells','SPPR106','0')
SetPrivateProfileString('Priest Spells','SPPR204','0')
SetPrivateProfileString('Priest Spells','SPPR107','0')
SetPrivateProfileString('Priest Spells','SPPR105','0')
SetPrivateProfileString('Priest Spells','SPPR202','0')
SetPrivateProfileString('Priest Spells','SPPR301','0')
SetPrivateProfileString('Priest Spells','SPPR450','0')
SetPrivateProfileString('Priest Spells','SPPR209','0')
SetPrivateProfileString('Priest Spells','SPPR109','0')
SetPrivateProfileString('Priest Spells','SPPR603','0')
SetPrivateProfileString('Priest Spells','SPPR725','0')
SetPrivateProfileString('Priest Spells','SPPR407','0')
SetPrivateProfileString('Priest Spells','SPPR508','0')
SetPrivateProfileString('Priest Spells','SPPR708','0')
SetPrivateProfileString('Priest Spells','SPPR311','0')
SetPrivateProfileString('Priest Spells','SPPR210','0')
SetPrivateProfileString('Priest Spells','SPPR313','0')
SetPrivateProfileString('Priest Spells','SPPR711','0')
SetPrivateProfileString('Priest Spells','SPPR606','0')
SetPrivateProfileString('Priest Spells','SPPR703','0')
SetPrivateProfileString('Priest Spells','SPPR514','0')
SetPrivateProfileString('Priest Spells','SPPR211','0')
SetPrivateProfileString('Priest Spells','SPPR729','0')
SetPrivateProfileString('Priest Spells','SPPR101','0')
SetPrivateProfileString('Priest Spells','SPPR517','0')
SetPrivateProfileString('Priest Spells','SPPR317','0')
SetPrivateProfileString('Priest Spells','SPPR416','0')
SetPrivateProfileString('Priest Spells','SPPR602','0')
SetPrivateProfileString('Priest Spells','SPPR312','0')
SetPrivateProfileString('Priest Spells','SPPR310','0')
SetPrivateProfileString('Priest Spells','SPPR705','0')
SetPrivateProfileString('Priest Spells','SPPR214','0')
SetPrivateProfileString('Priest Spells','SPPR611','0')
SetPrivateProfileString('Priest Spells','SPPR713','0')
SetPrivateProfileString('Priest Spells','SPPR314','0')
SetPrivateProfileString('Priest Spells','SPPR701','0')
SetPrivateProfileString('Priest Spells','SPPR203','0')
SetPrivateProfileString('Priest Spells','SPPR319','0')
SetPrivateProfileString('Priest Spells','SPPR402','0')
SetPrivateProfileString('Priest Spells','SPPR719','0')
SetPrivateProfileString('Priest Spells','SPPR506','0')
SetPrivateProfileString('Priest Spells','SPPR103','0')
SetPrivateProfileString('Priest Spells','SPPR702','0')
SetPrivateProfileString('Priest Spells','SPPR718','0')
SetPrivateProfileString('Priest Spells','SPPR727','0')
SetPrivateProfileString('Priest Spells','SPPR404','0')
SetPrivateProfileString('Priest Spells','SPPR412','0')
SetPrivateProfileString('Priest Spells','SPPR717','0')
SetPrivateProfileString('Priest Spells','SPPR206','0')
SetPrivateProfileString('Priest Spells','SPPR113','0')
SetPrivateProfileString('Priest Spells','SPPR712','0')
SetPrivateProfileString('Priest Spells','SPPR410','0')
SetPrivateProfileString('Priest Spells','SPPR604','0')
SetPrivateProfileString('Priest Spells','SPPR309','0')
SetPrivateProfileString('Priest Spells','SPPR213','0')
SetPrivateProfileString('Priest Spells','SPPR608','0')
SetPrivateProfileString('Priest Spells','SPPR108','0')
SetPrivateProfileString('Priest Spells','SPPR304','0')
SetPrivateProfileString('Priest Spells','SPPR350','0')
SetPrivateProfileString('Priest Spells','SPPR305','0')
SetPrivateProfileString('Priest Spells','SPPR414','0')
SetPrivateProfileString('Priest Spells','SPPR726','0')
SetPrivateProfileString('Priest Spells','SPPR706','0')
SetPrivateProfileString('Priest Spells','SPPR728','0')
SetPrivateProfileString('Priest Spells','SPPR207','0')
SetPrivateProfileString('Priest Spells','SPPR513','0')
SetPrivateProfileString('Priest Spells','SPPR201','0')
SetPrivateProfileString('Priest Spells','SPPR723','0')
SetPrivateProfileString('Priest Spells','SPPR721','0')
SetPrivateProfileString('Priest Spells','SPPR609','0')
SetPrivateProfileString('Priest Spells','SPPR409','0')
SetPrivateProfileString('Priest Spells','SPPR205','0')
SetPrivateProfileString('Priest Spells','SPPR212','0')
SetPrivateProfileString('Priest Spells','SPPR501','0')
SetPrivateProfileString('Priest Spells','SPPR307','0')
SetPrivateProfileString('Priest Spells','SPPR250','0')
SetPrivateProfileString('Priest Spells','SPPR405','0')
SetPrivateProfileString('Priest Spells','SPPR731','0')
SetPrivateProfileString('Priest Spells','SPPR607','0')
SetPrivateProfileString('Priest Spells','SPPR516','0')
SetPrivateProfileString('Priest Spells','SPPR715','0')
SetPrivateProfileString('Priest Spells','SPPR510','0')
SetPrivateProfileString('Priest Spells','SPPR503','0')
SetPrivateProfileString('Priest Spells','SPPR104','0')
SetPrivateProfileString('Priest Spells','SPPR413','0')
SetPrivateProfileString('Priest Spells','SPPR750','0')
SetPrivateProfileString('Priest Spells','SPPR315','0')
SetPrivateProfileString('Priest Spells','SPPR751','0')
SetPrivateProfileString('Priest Spells','SPPR102','0')
SetPrivateProfileString('Priest Spells','SPPR614','0')
SetPrivateProfileString('Priest Spells','SPPR612','0')
SetPrivateProfileString('Priest Spells','SPPR403','0')
SetPrivateProfileString('Priest Spells','SPPR732','0')
SetPrivateProfileString('Priest Spells','SPPR512','0')
SetPrivateProfileString('Priest Spells','SPPR710','0')
SetPrivateProfileString('Priest Spells','SPPR724','0')
SetPrivateProfileString('Priest Spells','SPPR704','0')
SetPrivateProfileString('Priest Spells','SPPR515','0')
SetPrivateProfileString('Priest Spells','SPPR111','0')
SetPrivateProfileString('Priest Spells','SPPR650','0')
SetPrivateProfileString('Priest Spells','SPPR601','0')
SetPrivateProfileString('Priest Spells','SPPR550','0')
SetPrivateProfileString('Priest Spells','SPPR610','0')
SetPrivateProfileString('Priest Spells','SPPR306','0')
SetPrivateProfileString('Priest Spells','SPPR509','0')
SetPrivateProfileString('Priest Spells','SPPR720','0')
SetPrivateProfileString('Priest Spells','SPPR415','0')
SetPrivateProfileString('Priest Spells','SPPR401','0')
SetPrivateProfileString('Priest Spells','SPPR707','0')
SetPrivateProfileString('Priest Spells','SPPR406','0')
SetPrivateProfileString('Priest Spells','SPPR730','0')
SetPrivateProfileString('Priest Spells','SPPR605','0')
SetPrivateProfileString('Priest Spells','SPPR302','0')
SetPrivateProfileString('Multiplayer','Session Password','')
SetPrivateProfileString('Multiplayer','Session Name','???????????')
SetPrivateProfileString('Multiplayer','Player Name','??????')
SetPrivateProfileString('Multiplayer','Enable Chat Menu','1')
SetPrivateProfileString('Multiplayer','Last Protocol Used','1')
SetPrivateProfileString('Multiplayer','Disable Banters','1')
SetPrivateProfileString('Keymap Miscellaneous','Hide Interface','0')
SetPrivateProfileString('Keymap Miscellaneous','Rest','122')
SetPrivateProfileString('Keymap Miscellaneous','Scroll Right','0')
SetPrivateProfileString('Keymap Miscellaneous','Left Interface','0')
SetPrivateProfileString('Keymap Miscellaneous','Hard Pause','112')
SetPrivateProfileString('Keymap Miscellaneous','Right Interface','0')
SetPrivateProfileString('Keymap Miscellaneous','Quick Loot','102')
SetPrivateProfileString('Keymap Miscellaneous','Scroll Down','0')
SetPrivateProfileString('Keymap Miscellaneous','Scroll Left','0')
SetPrivateProfileString('Keymap Miscellaneous','Scroll Up','0')
SetPrivateProfileString('Keymap Miscellaneous','Quick Load','105')
SetPrivateProfileString('Keymap Miscellaneous','Chat Window','0')
SetPrivateProfileString('Window','h','768')
SetPrivateProfileString('Window','y','159')
SetPrivateProfileString('Window','w','1024')
SetPrivateProfileString('Window','x','245')
SetPrivateProfileString('Window','Maximized','0')
SetPrivateProfileString('Window','Full Screen','1')
SetPrivateProfileString('Program Options','Volume SFX','100')
SetPrivateProfileString('Program Options','Volume Music','23')
SetPrivateProfileString('Program Options','Drop Capitals','1')
SetPrivateProfileString('Program Options','Volume Voices','100')
SetPrivateProfileString('Program Options','Path Search Nodes','32000')
SetPrivateProfileString('Program Options','Brightness Correction','0')
SetPrivateProfileString('Program Options','UI Edit Mode','0')
SetPrivateProfileString('Program Options','Disable Movies','0')
SetPrivateProfileString('Program Options','Strref On','0')
SetPrivateProfileString('Program Options','Sprite Mirror','0')
SetPrivateProfileString('Program Options','Volume Movie','66')
SetPrivateProfileString('Program Options','Volume Ambients','35')
SetPrivateProfileString('Program Options','Display Subtitles','1')
SetPrivateProfileString('Program Options','Font Name','')
SetPrivateProfileString('Program Options','Maximum Frame Rate','30')
SetPrivateProfileString('Program Options','Disable Cosmetic Attacks','1')
SetPrivateProfileString('Program Options','Tooltips','96')
SetPrivateProfileString('Program Options','3D Acceleration','1')
SetPrivateProfileString('Program Options','Active Campaign','0')
SetPrivateProfileString('Program Options','Translucent Shadows','1')
SetPrivateProfileString('Program Options','Cloud Saves Enabled','0')
SetPrivateProfileString('Program Options','Debug Mode','1')
