fontcolors['D'] = 'FFA9D4FF'
fontcolors['S'] = 'FF0066FF'
fontcolors['H'] = 'FF00B7FF'

styles['normal']['font'] = 'POSTANTI'
styles['normal']['point'] = 12
styles['normal_parchment']['font'] = 'REALMS'
styles['normal_parchment']['point'] = 10

styles['button']['font'] = 'REALMS'
styles['button']['point'] = 14
styles['button_parchment']['font'] = 'POSTANTI'
styles['button_parchment']['point'] = 14

styles['edit']['font'] = 'POSTANTI'
styles['edit']['point'] = 12
styles['edit_parchment']['font'] = 'POSTANTI'
styles['edit_parchment']['point'] = 12

styles['label']['font'] = 'REALMS'
styles['label']['point'] = 12
styles['label_parchment']['font'] = 'POSTANTI'
styles['label_parchment']['point'] = 12

styles['list']['font'] = 'STONESML'
styles['list']['point'] = 12
styles['list_parchment']['font'] = 'POSTANTI'
styles['list_parchment']['point'] = 12

styles['gold']['font'] = 'NORMAL'
styles['gold']['point'] = 12

styles['title']['font'] = 'SHERWOOD'
styles['title']['point'] = 20
styles['title']['color'] = 'H'

